### ISSUE TITLE
Not powering from inverter + sensor state unknown 

### ISSUE THREAD

**Issue by D43DBULL** [DeveloperDIY/solis-s6-home-assistant#2]
I have some trouble getting this to work. The esp 8266 is working when connected to usb and the sensors are showing, but all states are unknown.
And when I plug it in the inverter and unplug the usb the esp won't power on. I did bridge the ground to test if that would work, and it did power on the esp but still the sensors states where unknown. I also see no activatie (leds blinking) on the ttl to rs485 board, I have tried multiple boards but no changes.   

Can you spot something wrong? 
 
![20240911_215125](https://github.com/user-attachments/assets/63e7d79b-c07b-477c-867b-f7fc0c22fd65)
![20240911_215057](https://github.com/user-attachments/assets/d423997a-d679-4b0c-adcd-b65f2a344891)
![20240911_215150](https://github.com/user-attachments/assets/3523a17e-e24d-4693-adca-91e44a18072d)

(The wifi name and passwords I changed for posting)
```
esphome:
  name: solis-inverter

esp8266:
  board: d1_mini_pro

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome
  password: "password"

wifi:
  ssid: "Wifi name"
  password: "Wifi password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Solis-Inverter Fallback Hotspot"
    password: "password"

captive_portal:

uart:
  id: mod_bus
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600
  stop_bits: 1

modbus:
  id: modbus1

modbus_controller:
  - id: inverter
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10

sensor:
  - platform: modbus_controller
    modbus_controller_id: inverter
    id: solis_temp
    name: "Solis Temperature"
    address: 3041
    unit_of_measurement: C
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: solis_ac_power
    name: "Solis AC power"
    address: 3004
    unit_of_measurement: W
    register_type: read
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: solus_dc_power
    name: "Solis DC power"
    address: 3006
    unit_of_measurement: W
    register_type: read
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: solis_total_power
    name: "Solis total generated"
    address: 3008
    unit_of_measurement: kWh
    register_type: read
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: solis_today_power
    name: "Solis power generated today"
    address: 3014
    device_class: energy
    state_class: total_increasing
    unit_of_measurement: kWh
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: solis_yesterday_power
    name: "Solis power generated yesterday"
    address: 3015
    unit_of_measurement: kWh
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: solis_month_power
    name: "Solis power generated this month"
    address: 3010
    device_class: energy
    state_class: total_increasing
    unit_of_measurement: kWh
    register_type: read
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: solis_last_month_power
    name: "Solis power generated last month"
    address: 3012
    unit_of_measurement: kWh
    register_type: read
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: solis_year_power
    name: "Solis power generated this year"
    address: 3016
    device_class: energy
    state_class: total_increasing
    unit_of_measurement: kWh
    register_type: read
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: inverter
    id: last_year_power
    device_class: energy
    name: "Power generated last year"
    address: 3018
    unit_of_measurement: kWh
    register_type: read
    value_type: U_DWORD
```
